export EAR_DB_PATHNAME=$EAR_INSTALL_PATH/DB/EAR_App_summary_new_app
#export EAR_COEFF_DB_PATHNAME=$EAR_PATH/COEFFICIENTS/Coefficients
export EAR_COEFF_DB_PATHNAME=/home/xjcorbalan/EAR/COEFFICIENTS_TURBO/COEFF_COLLAB_
export EAR_PERFORMANCE_ACCURACY=2000000
export EAR_LEARNING_PHASE=0
export EAR_TURBO=0
export EAR_DYNAIS_LEVELS=4
export EAR_DYNAIS_WINDOW_SIZE=200

export EAR_LIBRARY_PATH=$EAR_INSTALL_PATH/lib/libEAR.so
export EAR_LIBRARY_GUI_PATH=$EAR_INSTALL_PATH/lib/libEARgui.so

export EAR_GUI_PATH=$EAR_TMP/GUI

#export EAR_POWER_POLICY=MONITORING_ONLY
#export EAR_POWER_POLICY=MIN_TIME_TO_SOLUTION
#export EAR_POWER_POLICY=MIN_ENERGY_TO_SOLUTION
#export EAR_MIN_PERFORMANCE_EFFICIENCY_GAIN=0.7
#export EAR_PERFORMANCE_PENALTY=0.1

export EAR_RESET_FREQ=0



