RLPATH = $(subst $(SRCDIR),.,$(shell pwd))
RLPATH = $(shell realpath $(SRCDIR) --relative-to=$(shell pwd))

######## RULES

depend: rdepend

rdepend: $(wildcard ./*.c)
	@ rm -f ./.depend
	@ $(CC) -I $(RLPATH) -MM -MG $^ >> ./.depend;

depend-clean:
	@ rm -f .depend

######## ADDITIONAL

rclean:
	@ rm -f *.o *.a *.so

%.gclean:
	@ rm -f $($*_BINS)

%.ginstall:
	@ (cp $($*_BINS) $($*_PATH) && cd $($*_PATH) && chmod $($*_PERM) $($*_BINS))

-include .depend
