######## RULES

%.gclean:
	@ rm -f $($*_BINS)

rclean:
	rm -f *.o *.a *.so

%.ginstall:
ifdef CHOWN_USR
	@ (cd $($*_PATH) && chown $(CHOWN_USR) $($*_BINS))
endif
ifdef CHOWN_GRP
	@ (cd $($*_PATH) && chgrp $(CHOWN_GRP) $($*_BINS))
endif
	@ (cp $($*_BINS) $($*_PATH) && cd $($*_PATH) && chmod $($*_PERM) $($*_BINS))

-include .extra